name: Cache Demo
on: [push]
jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: prime-cache-241c041
      id: cache-step
      uses: actions/cache@v4
      with:
        key: cache-241c041
        path: ~/.npm
    - name: Echo cache result
      run: echo "Cache outcome: ${{ steps.cache-step.outputs.cache-hit }}"
